OBJS += ppc/cpu.o                                                       \
        ppc/float_dsp_init.o                                            \

ALTIVEC-OBJS += ppc/float_dsp_altivec.o                                 \
                ppc/util_altivec.o                                      \
